language: ruby
script: "bundle exec rake"
env:
  - CI=true
rvm:
  - 2.0.0
  - 2.1
  - rbx-2
gemfile:
  - Gemfile
notifications:
  recipients:
    - smaginsergey1310@gmail.com
branches:
  only:
    - master
